config/routes.rb
Publisher::Application.routes.draw do
  resources :subscribers

  resources :magazines

  match 'subscriber/:id/subscription_list' => 'subscribers#subscription_list', :as => :subscription_list
  match 'subscribed' => 'subscriptions#subscribed'
  resources :subscriptions, only: [:create, :destroy]

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  attr_accessible :description, :editor, :title
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :address, :name
  has_many :subscriptions
  has_many :magazines, through: :subscriptions
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :duration, :magazine_id, :start, :subscriber_id
  belongs_to :magazine
  belongs_to :subscriber
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  # GET /magazines
  # GET /magazines.json
  def index
    @magazines = Magazine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @magazines }
    end
  end

  # GET /magazines/1
  # GET /magazines/1.json
  def show
    @magazine = Magazine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @magazine }
    end
  end

  # GET /magazines/new
  # GET /magazines/new.json
  def new
    @magazine = Magazine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @magazine }
    end
  end

  # GET /magazines/1/edit
  def edit
    @magazine = Magazine.find(params[:id])
  end

  # POST /magazines
  # POST /magazines.json
  def create
    @magazine = Magazine.new(params[:magazine])

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render json: @magazine, status: :created, location: @magazine }
      else
        format.html { render action: "new" }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /magazines/1
  # PUT /magazines/1.json
  def update
    @magazine = Magazine.find(params[:id])

    respond_to do |format|
      if @magazine.update_attributes(params[:magazine])
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine = Magazine.find(params[:id])
    @magazine.destroy

    respond_to do |format|
      format.html { redirect_to magazines_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end

  def subscription_list
    @subscriber = Subscriber.find(params[:id])
    @magazines = Magazine.find(:all)
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def create
    @subscriber = Subscriber.find(params[:subscription][:subscriber_id])
    @subscriber.subscriptions.build(magazine_id: params[:subscription][:magazine_id])
    @subscriber.save
    render 'subscriptions/subscribed'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Publisher</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/magazines/_form.html.erb
<%= form_for(@magazine) do |f| %>
  <% if @magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% @magazine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :editor %><br />
    <%= f.text_field :editor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<h1>Editing magazine</h1>

<%= render 'form' %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<h1>Listing magazines</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Editor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @magazines.each do |magazine| %>
  <tr>
    <td><%= magazine.title %></td>
    <td><%= magazine.description %></td>
    <td><%= magazine.editor %></td>
    <td><%= link_to 'Show', magazine %></td>
    <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
    <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New magazine</h1>

<%= render 'form' %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @magazine.title %>
</p>

<p>
  <b>Description:</b>
  <%= @magazine.description %>
</p>

<p>
  <b>Editor:</b>
  <%= @magazine.editor %>
</p>

<h2>Subscribers</h2>
<ol>
	<% @magazine.subscribers.each do |subscriber| %>
		<li><%= subscriber.name %></li>
	<% end %>
</ol>

<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%= link_to 'Back', magazines_path %>

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.name %></td>
    <td><%= subscriber.address %></td>
    <td><%= link_to 'Show', subscriber %></td>
    <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
    <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Subscribe', subscription_list_url(subscriber) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @subscriber.name %>
</p>

<p>
  <b>Address:</b>
  <%= @subscriber.address %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>

<h2>Your Subscriptions</h2>
<ol>
	<% @subscriber.subscriptions.each do |sub| %>
		<li><%= sub.magazine.title %></li>
	<% end %>
</ol>

app/views/subscribers/subscription_list.html.erb
<h1>Subscribing <%= @subscriber.name %></h1>
<h2>Magazine Choices</h2>
<ul>
<% @magazines.each do |magazine| %>
	<li>
		<%= magazine.title %>
		<% #OPTIMIZE turn this into a button_to %>
		<%= form_for(@subscriber.subscriptions.build(magazine_id: magazine.id)) do |f|%>
			<%= f.hidden_field :subscriber_id %>		
			<%= f.hidden_field :magazine_id %>
			<%= f.submit "Subscribe" %>
		<% end %>
	</li>
<% end %>
</ul>

app/views/subscriptions/subscribed.html.erb
<h2>Congrats  <%= link_to @subscriber.name, @subscriber %> subscription was successful!</h2>